default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: politick_development

test:
  <<: *default
  database: politick_test

production:
  <<: *default
  database: politick_production
  username: politick
  password: <%= ENV['POLITICK_DATABASE_PASSWORD'] %>
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>
